#!/bin/sh 

set -e

if [ "$1" = "disappear" -o "$1" = "remove" ]
then
	if [ ! -z `which update-inetd` ]
    then
        update-inetd --disable ftp
    fi
fi

if [ "$1" = "purge" ]
then
    rm -rf /etc/proftpd 
    rm -rf /var/log/proftpd
    rm -rf /srv/ftp
    rm -f /etc/logrotate.d/proftpd-basic
    userdel --remove --force proftpd || true
    userdel ftp || true
    update-rc.d proftpd remove >/dev/null || exit $?
fi



