#!/bin/sh
set -e
# Automatically added by dh_installsystemd/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'qemu-guest-agent.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/qemu-guest-agent" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native qemu-guest-agent stop || exit 1
fi
# End automatically added section
