#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.7.1ubuntu1
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.UPower.conf 0.99.9-2\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12.7.1ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'upower.service' >/dev/null || true
fi
# End automatically added section
